# Generated by Django 5.1.5 on 2025-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pejapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
