# Generated by Django 5.1.5 on 2025-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pejapp", "0003_post_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
