# Generated by Django 5.1.5 on 2025-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pejapp", "0004_post_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modified_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
