# Generated by Django 5.1.5 on 2025-02-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pejapp", "0005_post_modified_flag_post_original_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="display_name",
        ),
    ]
