# Generated by Django 5.1.5 on 2025-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pejapp", "0006_remove_post_display_name_remove_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
